# =============================================================================
# Data Discovery Agent - Docker Compose Configuration
# =============================================================================
# For local development and testing of the MCP service
# =============================================================================

version: '3.8'

services:
  # MCP Service
  mcp-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-discovery-mcp
    image: data-discovery-agent-mcp:latest
    
    # Environment variables from .env file
    env_file:
      - .env
    
    # Additional environment variables
    environment:
      - LOG_LEVEL=INFO
      - MCP_SERVER_NAME=data-discovery-agent
      - MCP_SERVER_VERSION=1.0.0
      - MCP_TRANSPORT=http  # Use HTTP for containerized deployment
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8080
    
    # Port mapping for HTTP transport
    ports:
      - "8080:8080"
    
    # Mount application code for live reload during development
    volumes:
      - ./src:/app/src:ro
      - ./config:/app/config:ro
      # Mount GCP credentials for local development
      # Uncomment if using service account key file
      # - ~/.config/gcloud:/home/mcp/.config/gcloud:ro
    
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Network
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

# =============================================================================
# Usage:
#
# 1. Copy .env.example to .env and fill in your values
# 2. Start the service:
#    docker-compose up -d
#
# 3. View logs:
#    docker-compose logs -f mcp-service
#
# 4. Stop the service:
#    docker-compose down
#
# 5. Rebuild after code changes:
#    docker-compose up -d --build
# =============================================================================

