# =============================================================================
# Service Account for MCP Service
# =============================================================================
# Uses Workload Identity to authenticate with Google Cloud
# =============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-service-sa
  namespace: data-discovery
  labels:
    app: data-discovery-agent
    component: mcp-service
  annotations:
    # Workload Identity binding
    # Replace PROJECT_ID with your GCP project ID
    iam.gke.io/gcp-service-account: mcp-service@PROJECT_ID.iam.gserviceaccount.com

---
# =============================================================================
# Workload Identity Setup Instructions:
# =============================================================================
#
# 1. Create GCP service account (done via Terraform):
#    gcloud iam service-accounts create mcp-service \
#      --project=PROJECT_ID
#
# 2. Grant IAM roles (done via Terraform):
#    - roles/discoveryengine.user (Vertex AI Search)
#    - roles/storage.objectViewer (GCS read access)
#    - roles/bigquery.jobUser (BigQuery queries)
#    - roles/bigquery.metadataViewer (BigQuery metadata)
#
# 3. Bind K8s SA to GCP SA:
#    gcloud iam service-accounts add-iam-policy-binding \
#      mcp-service@PROJECT_ID.iam.gserviceaccount.com \
#      --role roles/iam.workloadIdentityUser \
#      --member "serviceAccount:PROJECT_ID.svc.id.goog[data-discovery/mcp-service-sa]"
#
# 4. Update the annotation above with your project ID
#
# =============================================================================

