# GenAI Toolbox Configuration
# Data Discovery Agent - Read-Only Tools for BigQuery and Dataplex
# SR-2A Compliant: No source data writes

# General Configuration
toolbox:
  name: "data-discovery-toolbox"
  version: "1.0.0"
  environment: "dev"
  
  # Read-only mode enforcement
  security:
    read_only_mode: true
    validate_operations: true
    block_ddl: true
    block_dml: true
    allowed_operations:
      - "SELECT"
      - "DESCRIBE"
      - "SHOW"
      - "EXPLAIN"
    
  # Connection settings
  connection:
    timeout_seconds: 30
    max_retries: 3
    pool_size: 10
    
  # Audit logging
  audit:
    enabled: true
    log_all_queries: true
    log_level: "INFO"

# BigQuery Tools Configuration
bigquery:
  enabled: true
  project_id: "lennyisagoodboy"
  
  tools:
    # Tool: bigquery-get-table-info
    - name: "bigquery-get-table-info"
      enabled: true
      description: "Retrieve metadata about BigQuery tables, views, and materialized views"
      read_only: true
      parameters:
        default_dataset: null
        include_schema: true
        include_partition_info: true
        include_clustering_info: true
      
    # Tool: bigquery-execute-sql
    - name: "bigquery-execute-sql"
      enabled: true
      description: "Execute read-only SQL queries against BigQuery"
      read_only: true
      validation:
        # Strict validation to ensure only SELECT queries
        allowed_statements:
          - "SELECT"
          - "WITH"
        blocked_statements:
          - "INSERT"
          - "UPDATE"
          - "DELETE"
          - "CREATE"
          - "DROP"
          - "ALTER"
          - "TRUNCATE"
          - "MERGE"
        max_bytes_billed: 10737418240  # 10 GB limit
        max_results: 10000
        use_query_cache: true
      parameters:
        default_dataset: null
        use_legacy_sql: false
        dry_run_available: true

  # Connection configuration
  connection:
    service_account: "data-discovery-agent@lennyisagoodboy.iam.gserviceaccount.com"
    use_workload_identity: true
    location: "us-central1"

# Dataplex Tools Configuration
dataplex:
  enabled: true
  project_id: "lennyisagoodboy"
  
  tools:
    # Tool: dataplex-get-lineage
    - name: "dataplex-get-lineage"
      enabled: true
      description: "Retrieve data lineage information from Dataplex"
      read_only: true
      parameters:
        max_depth: 5
        include_column_lineage: true
        
    # Tool: dataplex-get-data-quality
    - name: "dataplex-get-data-quality"
      enabled: true
      description: "Retrieve data quality scan results from Dataplex"
      read_only: true
      parameters:
        include_historical: true
        max_results: 100
        
    # Tool: dataplex-get-data-profile
    - name: "dataplex-get-data-profile"
      enabled: true
      description: "Retrieve data profiling results from Dataplex"
      read_only: true
      parameters:
        include_statistics: true
        include_distributions: true

  # Connection configuration  
  connection:
    service_account: "data-discovery-agent@lennyisagoodboy.iam.gserviceaccount.com"
    use_workload_identity: true
    location: "us-central1"

# Data Catalog Tools Configuration
datacatalog:
  enabled: true
  project_id: "lennyisagoodboy"
  
  tools:
    # Tool: datacatalog-search
    - name: "datacatalog-search"
      enabled: true
      description: "Search Data Catalog for assets"
      read_only: true
      parameters:
        max_results: 100
        
    # Tool: datacatalog-get-entry
    - name: "datacatalog-get-entry"
      enabled: true
      description: "Get detailed information about a Data Catalog entry"
      read_only: true
  
  connection:
    service_account: "data-discovery-agent@lennyisagoodboy.iam.gserviceaccount.com"
    use_workload_identity: true

# Future Data Sources (Disabled for initial deployment)
cloudsql:
  enabled: false
  # Configuration to be added when needed
  
alloydb:
  enabled: false
  # Configuration to be added when needed

# Tool Registry
# Maps tool names to their implementations
tool_registry:
  bigquery-get-table-info:
    provider: "genai-toolbox"
    category: "metadata"
    
  bigquery-execute-sql:
    provider: "genai-toolbox"
    category: "query"
    
  dataplex-get-lineage:
    provider: "genai-toolbox"
    category: "lineage"
    
  dataplex-get-data-quality:
    provider: "genai-toolbox"
    category: "quality"
    
  dataplex-get-data-profile:
    provider: "genai-toolbox"
    category: "profiling"

# MCP (Model Context Protocol) Configuration
mcp:
  enabled: true
  protocol_version: "1.0"
  endpoint:
    host: "0.0.0.0"
    port: 8080
    path: "/mcp"
  
  # Health check endpoint
  health_check:
    enabled: true
    path: "/health"
    port: 8080
  
  # Metrics endpoint
  metrics:
    enabled: true
    path: "/metrics"
    port: 8080

# Rate Limiting
rate_limiting:
  enabled: true
  requests_per_minute: 60
  burst: 10

# Caching
caching:
  enabled: true
  ttl_seconds: 300  # 5 minutes
  max_size_mb: 100

# Error Handling
error_handling:
  retry_on_timeout: true
  retry_on_rate_limit: true
  max_retries: 3
  backoff_multiplier: 2

